name: oidc-poc-cli
on:
    push:
        branches:
            - '*'
jobs:
    build-publish-python:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository    
              uses: actions/checkout@v4
              
            - name: Setup JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env: 
                JF_URL: https://${{ vars.JF_URL }}/
                JFROG_CLI_LOG_LEVEL: DEBUG
              with:
                  oidc-provider-name: github-carmit-project-1

            - name: configure jfrog environment
              run: |
                echo "verify jfrog cli"                
                jf --version
                jf pip-config --repo-resolve=python-virtual       
            - name: configure environment
              run: |               
                echo "verify python"                
                python --version
                pip --version
                echo "setup python"                
                python3 -m pip install --upgrade pip setuptools wheel sigstore
                wheel -h
                pip show setuptools
                echo $VIRTUAL_ENV
                
            - name: build project
              run: |
                echo "PWD"
                pwd
                echo "ls"
                ls -ltr 
                echo "ls pythonExample"
                ls -ltr  pythonExample
                echo "install dependencies"
                jf pip install -r requirements.txt --build-name=my-pip-build --build-number=1 --module=jfrog-python-example
                echo "Build"
                python setup.py sdist bdist_wheel
                cd dist && echo "hashes=$(sha256sum * | base64 -w0)" >> $GITHUB_OUTPUT
                echo "$GITHUB_OUTPUT"
            - name: publish project
              run: |
                jf rt u dist/ python-virtual/example-projects/ --build-name=my-pip-build --build-number=1 --module=jfrog-python-example --project ${{ vars.JF_PROJECT_KEY }} 
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3    
                
            - name: Authenticate Docker
              uses: docker/login-action@v3
              with:
                registry: ${{ vars.JF_URL }}
                username: ${{ vars.JF_DOCKER_USER }} 
                password: ${{ secrets.JF_DOCKER_TOKEN }} 
    
                
            - name: Build Docker image    
              uses: docker/build-push-action@v5
              id: build
              with:
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ vars.JF_URL }}/docker-local/carmit-testing:3
                
            - name: docker scan
              env:
                ACTIONS_STEP_DEBUG: true
                JFROG_CLI_LOG_LEVEL: 'DEBUG'
              run: |                
                 jf docker scan ${{ vars.JF_URL }}/docker-local/carmit-testing:3
                 jf docker push ${{ vars.JF_URL }}/docker-local/carmit-testing:3
                 
            - name: publish build info
              run: |
                jf rt bce my-pip-build 1
                jf rt bp my-pip-build 1  --project ${{ vars.JF_PROJECT_KEY }}
                
                
                
