name: oidc-poc
on:
    push:
        branches:
            - '*'
jobs:
    auth:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
        
            - name: Get id token
              run: |
                ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=carmit_project_1" | jq .value | tr -d '"')
                echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
                echo "ID_TOKEN=${ID_TOKEN}"
                echo "env: $GITHUB_ENV"
                
            - name: Exchange token with access
              env:
                    ID_TOKEN: ${{env.ID_TOKEN}}
                    ARTIFACTORY_URL: https://carmittrial1.jfrog.io
              run: |
                    ACCESS_TOKEN=$(curl -XPOST "https://carmittrial1.jfrog.io/token" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:access_token\", \"subject_token\": \"$ID_TOKEN\", \"provider_name\": \"github-carmit-project-1\"}" | jq .access_token | tr -d '"')
                    echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
            
            
