name: oidc-poc-cli
on:
    push:
        branches:
            - '*'
jobs:
    build-publish-go:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository    
              uses: actions/checkout@v4
              
            - name: Setup JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env:
                JF_URL: ${{ secrets.JF_URL }} 
              with:
                  oidc-provider-name: github-carmit-project-1
                  
            - name: configure golang repo

