name: oidc-poc 
on:
    push:
        branches:
            - '*'
jobs:
    auth:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
           - uses: jfrog/setup-jfrog-cli@v3
             env:
               JF_URL: https://carmittrial1.jfrog.io
             with:
                oidc-provider-name: github-carmit-project-1 
                oidc-audience: carmit_project_1
