name: oidc-poc-cli
on:
    push:
        branches:
            - '*'
jobs:
    build-publish-python:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository    
              uses: actions/checkout@v4
              
            - name: Setup JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env:
                JF_URL: ${{ secrets.JF_URL }} 
              with:
                  oidc-provider-name: github-carmit-project-1
                  
            - name: configure environment
              run: |
                echo "verify jfrog cli"                
                jf --version
                jf pip-config --repo-resolve=python-virtual
                echo "verify python"                
                python --version
                pip --version
                echo "setup python"                
                python3 -m pip install --upgrade pip setuptools wheel
                wheel -h
                pip show setuptools
                echo $VIRTUAL_ENV
                
            - name: build project
              run: |
              
