name: oidc-poc-cli
on:
    push:
        branches:
            - '*'
jobs:
    auth:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository    
              uses: actions/checkout@v4
              
            - name: Setup JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env:
                JF_URL: ${{ secrets.JF_URL }} 
              with:
                  oidc-provider-name: github-carmit-project-1
                  
            - name: configure golang repo
              run: |
               echo "configure golang repo"
               jf go-config --repo-resolve=<GO_RESOLVE_REPO> --repo-deploy=golang-remote
               jf go build --build-name=my-build --build-number=1 
               jf go-publish v1.0.0 --build-name=my-build --build-number=1
               jf rt bce my-build 1
               jf rt bp my-build 1
