name: oidc-poc-cli
on:
    push:
        branches:
            - '*'
jobs:
    build-publish-go:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository    
              uses: actions/checkout@v4
              
            - name: Setup JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env:
                JF_URL: ${{ secrets.JF_URL }} 
              with:
                  oidc-provider-name: github-carmit-project-1
                  
            - name: configure golang repo
              run: |
               echo "configure golang repo"
               jf config s
               jf go-config  --server-id-resolve setup-jfrog-cli-server --repo-resolve=golang-remote
            - name: build
              run: |
               echo "build go"
               jf go build --build-name=my-build --build-number=1 
            - name: publish
              run: |
                echo "publish"
                jf go-publish golang-local v1.0.0 --build-name=my-build --build-number=1 --server-id setup-jfrog-cli-server
            - name: build-info
              run: |
                echo "build-info"
                jf rt bce my-build 1
                jf rt bp my-build 1
