name: oidc-poc-cli
on:
    push:
        branches:
            - '*'
jobs:
    build-publish-python:
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository    
              uses: actions/checkout@v4
              
            - name: Setup JFrog CLI
              uses: jfrog/setup-jfrog-cli@v4
              env:
                JF_URL: ${{ secrets.JF_URL }} 
              with:
                  oidc-provider-name: github-carmit-project-1

            - name: configure jfrog environment
              run: |
                echo "verify jfrog cli"                
                jf --version
                jf pip-config --repo-resolve=python-virtual       
            - name: configure environment
              run: |               
                echo "verify python"                
                python --version
                pip --version
                echo "setup python"                
                python3 -m pip install --upgrade pip setuptools wheel
                wheel -h
                pip show setuptools
                echo $VIRTUAL_ENV
                
            - name: build project
              run: |
                jf pip install -r requirements.txt --build-name=my-pip-build --build-number=1 --module=jfrog-python-example
            - name: package project
              run: |
                python setup.py sdist bdist_wheel
            - name: publish project
              run: |
                jf rt u dist/ pypi/ --build-name=my-pip-build --build-number=1 --module=jfrog-python-example
            - name: publish build info
              run: |
                jf rt bce my-pip-build 1
                jf rt bp my-pip-build 1
                
                
                
